server:
  port: 8093
spring:
  application:
    name: input-demo
  cloud:
     instance-count: 1
     instance-index: 0
     stream:
        kafka:
          binder:
            brokers: ﻿cloudserver1.himelon.com:9092
            zk-nodes: ﻿cloudserver1.himelon.com:2182
            auto-add-partitions: true
            auto-create-topics: true
            min-partition-count: 3
        bindings:
          input:
            destination: event-demo
            group: s1
            consumer:
              autoCommitOffset: false
              concurrency: 1
              partitioned: true
