server:
  port: 8886
spring:
  application:
    name: spring-cloud-eureka-client
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7000/eurekaServer/eureka

feign:
  hystrix:
    enabled: true
hystrix:
  command:
    ##全局方法使用default
    HelloClient#toHello():
      execution:
        isolation:
          thread:
          ##超时时间
            timeoutInMilliseconds: 500
      circuitBreaker:
      ##每秒3次请求
        requestVolumeThreshold: 3

