server:
  port: 8091
spring:
  application:
    name: output-demo
  cloud:
     stream:
        kafka:
          binder:
            brokers: ﻿cloudserver1.himelon.com:9092
            zk-nodes: ﻿cloudserver1.himelon.com:2182
            auto-add-partitions: true
            auto-create-topics: true
            min-partition-count: 3
        bindings:
          output:
            destination: event-demo
            content-type: text/plain
            producer:
              partitionCount: 3
